### ISSUE TITLE
Props are not working correctly

### ISSUE THREAD

**Issue by Ulyanov-programmer** [thewebartisan7/posthtml-components#32]
I wrote the following code in the "head" component:

```html
<!-- src/head.html -->

<script props>
  module.exports = {
    text: props.text || 'Default text'
  }
</script>
<div>
  {{ text }}
</div>
```
And called this component from another file:
```html
<!-- src/index.html -->

<x-head text='some text'></x-head>
```

After starting, I got the following error:
```powershell

Error in plugin "gulp-posthtml"
Message:
    'text' is not defined
Details:
    domainEmitter: [object Object]
    domainThrown: false

Stack:
ReferenceError: 'text' is not defined
    at placeholders (G:\gulp_multitool\node_modules\posthtml-expressions\lib\placeholders.js:73:19)
    at G:\gulp_multitool\node_modules\posthtml-expressions\lib\index.js:198:14
    at Array.reduce (<anonymous>)
    at walk (G:\gulp_multitool\node_modules\posthtml-expressions\lib\index.js:185:27)
    at G:\gulp_multitool\node_modules\posthtml-expressions\lib\index.js:229:22
    at Array.reduce (<anonymous>)
    at walk (G:\gulp_multitool\node_modules\posthtml-expressions\lib\index.js:185:27)
    at G:\gulp_multitool\node_modules\posthtml-expressions\lib\index.js:229:22
    at Array.reduce (<anonymous>)
    at walk (G:\gulp_multitool\node_modules\posthtml-expressions\lib\index.js:185:27)
```

I use your library in gulp, so I connect it:
```js
.pipe(posthtml([
      component({
        root: './src',
      }),
    ], {}))
```

This is very strange, because I wrote +- just as it is written in the documentation. 
If I delete the line `{{ text }}`, _it works_ (the head.html file will be connected).
I hope I just overlooked something.

The full file code of index.html and head.html:
<details><summary>Details</summary>

```htm
<!DOCTYPE html>
<html lang="ru-RU">

<!-- ./src/head.html -->
<script props>
  module.exports = {
    text: props.text || 'Default text'
  }
</script>
<div>
{{ text }}
</div>

<head>
  <meta charset='UTF-8'>
  <meta http-equiv='X-UA-Compatible' content='IE=edge'>
  <meta name='viewport' content='width=device-width, initial-scale=1.0'>
  <!-- maximum-scale=1.0, user-scalable=0 does not allow content to be scaled on Android. -->
  <!-- Disables forced link for phone number on iOS -->
  <meta name='format-detection' content='telephone=no'>

  <meta name='description' content='description'>
  <meta name='theme-color' content='#000000'>
  <link rel='icon' href='./img/favicon.svg'>
  <link rel='mask-icon' href='./img/favicon.svg' color='#000000'>
  <!-- <link rel='apple-touch-icon' href='apple-touch-icon.png'> -->
  <!-- <link rel='manifest' href='manifest.json'> -->

  <!-- SEO
	<meta name='keywords' content='keyword1,'>
	<meta name='robots' content='none,noindex,nofollow,noimageindex,noarchive,nosnippet'>
	<meta name='Author' content='Author'>
	<meta name='Copyright' content='Copyright'>
	<meta name='Address' content='Address'> 
	<! - Redirect (reload) the page. Delay in seconds; url=Site / page address ->
	<meta http-equiv='refresh' content='seconds; url = URL'>

	Facebook
	<! - site localization, for the Russian-language site ru_RU ->
	<meta property='og:locale' content='ru_RU'>
	<! - content type, default is article ->
	<meta property='og:type' content='article'>
	<! - the title of the page that will be displayed in the post of the social network ->
	<meta property='og:title' content='META tags'>
	<! - page description ->
	<meta property='og:description' content='Description of the page about META tags'>
	<! - link to the image that will be published in the post ->
	<meta property='og:image' content='path'>
	<! - link to the current page ->
	<meta property='og: url' content='path'>
	<! - site name ->
	<meta property='og:site_name' content='Freelancer for life'>

	Twitter
	<! - Map type, default is summary ->
	<meta name='twitter: card' content='summary'>
	<! - Author name / login ->
	<meta name='twitter: site' content='Ivan'>
	<! - Page title ->
	<meta name='twitter: title' content='META tags'>
	<! - Page description ->
	<meta name='twitter: description' content='about META tags'>
	<! - Link to image ->
	<meta name='twitter: image' content='path'>
	-->

  <title>
  </title>

  <!-- /-/ General stylesheets -->
  <link rel='stylesheet' href='styles/general/nullStyle.css'>
  <link rel='stylesheet' href='styles/general/fonts.css'>
  <link rel='stylesheet' href='styles/general/header.css'>
  <link rel='stylesheet' href='styles/general/footer.css'>
  <link rel='stylesheet' href='styles/general/general.css'>

</head>
```

```htm
<!-- ./src/index.html -->
<x-head text="some text"></x-head>

<body>
  <main class='main'>
    <img src='img/logo.png' loading='lazy' alt='some alt' width=125 height=150>
  </main>
</body>

</html>
```
</details>

**Comment by thewebartisan7** [comment]
Can you please provide a repo with the same setup you are using so that I can reproduce this issue?

**Comment by Ulyanov-programmer** [comment]
I made a branch of my repository with project files.
It is started by installing node_modules (I'm not sure if `npm ci` will install everything correctly, dev branch ¯\\_(ツ)_/¯), and then by the `gulp` command.
You may be interested in debugging the file `./gulp/html.js` .

https://github.com/Ulyanov-programmer/gulp_multitool/tree/temporary

**Comment by thewebartisan7** [comment]
I don't see posthtml installed here https://github.com/Ulyanov-programmer/gulp_multitool/blob/master/package.json

**Comment by Ulyanov-programmer** [comment]
You looked in the master branch, switch to temporary (in theory, you should have been sent to it by the link).
![image](https://user-images.githubusercontent.com/66691708/233440379-7a94ff2e-862c-4daa-8a46-d89006170b0e.png)

**Comment by thewebartisan7** [comment]
The problem happen because in  `gulp/paths.js` you add to process all .html files, so also the head.html is being processed as HTML entry point. You have to move this file inside components folder as you have configured to skip this folders from being processed by gulp

If you try to set path to process only index.html then it's works fine.

In `gulp/paths.js` change `paths.src.html`:

```js
  scr: {
    html: [`${source}/index.{html,htm}`, `!${source}/components/*.{html,htm}`],
  },
```

then it works fine. Or just move inside components.

Apart this, for a layout file I would suggest below approach:

```html
// src/layout.html
<script props>

  module.exports = {
    title: props.title || 'Default title'
  }
</script>
<!DOCTYPE html>
<html lang="ru-RU">
<head>
  <meta charset='UTF-8'>
  <meta http-equiv='X-UA-Compatible' content='IE=edge'>
  <!-- stack for push meta see https://thewebartisan7.github.io/posthtml-components/docs.html#stacks -->
  <stack name="meta"></stack>
  <title>{{ title }}</title>

  <!-- Stack for push CSS see https://thewebartisan7.github.io/posthtml-components/docs.html#stacks -->
 <stack name="styles"></stack>
</head>
<body>

 <header>
  <!-- In case you want also to add a header or any other content use slot see https://thewebartisan7.github.io/posthtml-components/docs.html#slots -->
 <slot:header></slot:header>
 </header>
  <main class='main'>
    <yield></yield>
  </main>

  <!-- Stack for push JS see https://thewebartisan7.github.io/posthtml-components/docs.html#stacks -->
 <stack name="scripts"></stack>
</body>

</html>
```

Then use your layout when creating a page

```html
// src/page.html

<x-layout title="My page">

  <fill:header>Header content</fill:header>

  <div>Main content</div>
</x-layout>

<push name="meta">
<meta name='keywords' content='keyword1,'>
</push>

<push name="styles">
<!-- push styles -->
</push>

<push name="scripts">
<!-- push scripts -->
</push>
```

I didn't test above code, so it may contain some issues in case you just copy paste.

**Comment by Ulyanov-programmer** [comment]
I have yet to fully familiarize myself with the library (I just installed it, I haven't really tried it), thank you for the tips on page layout!

There is no need for a strong path change, I just moved the head to the components folder. 

### For those looking for an answer: I moved the `head.html` file to a folder that is _ignored by gulp_.

**Comment by thewebartisan7** [comment]
> For those looking for an answer: I moved the `head.html` file to a folder that is _ignored by gulp_.

Yes that it's the right way. However in that case you have also to set folders options 

```js
.pipe(posthtml([
      component({
        root: './src',
        folders: ['components']
      }),
    ], {}))

or use your component with `<x-components.head>`
